language: java

 #有定制化开发环境需要，默认false，
 #不开启容器，编译效率高
sudo: false 

# 邮箱通知
notifications:    
  email: false

#启用codecov
codecov: true

jdk:
    - oraclejdk8

install: cd kin-picture-processing && mvn install -DskipTests=false -Dmaven.javadoc.skip=true -Dgpg.skip=true

after_success:
    - bash <(curl -s https://codecov.io/bash)  -t 5da3a823-3e30-4093-b028-cc65a392abce

